module CssTidy

	class Parser
		# All whitespace allowed in CSS
		WHITESPACE = [' ',"\n","\t","\r","\x0B"]

		# All CSS tokens used by tidy
		TOKENS = %w[/ @ } { , : = ' " ( , \\ ! $ % & ) * + . < > ? [ ] ^ ` | ~]

		# All CSS units (CSS 3 units included)
		units = ['in','cm','mm','pt','pc','px','rem','em','%','ex','gd','vw','vh','vm','deg','grad','rad','ms','s','khz','hz']

		# Available at-rules
		AT_RULES = {
			'page' => 'IN_SELECTOR',
			'font-face' => 'IN_SELECTOR',
			'charset' => 'IN_VALUE',
			'import' => 'IN_VALUE',
			'namespace' => 'IN_VALUE',
			'media' => 'IN_AT_BLOCK'
		}

		# Properties that need a value with unit
		unit_values = [
			'background', 'background-position',
			'border', 'border-top', 'border-right', 'border-bottom', 'border-left', 'border-width',
			'border-top-width', 'border-right-width', 'border-left-width', 'border-bottom-width',
			'bottom', 'border-spacing', 'font-size', 'height', 'left',
			'margin', 'margin-top', 'margin-right', 'margin-bottom', 'margin-left',
			'max-height', 'max-width', 'min-height', 'min-width', 'outline-width',
			'padding', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left',
	    'position', 'right', 'top', 'text-indent', 'letter-spacing', 'word-spacing', 'width'
		]

		# Properties that allow <color> as value
		color_values = [
			'background-color', 'border-color', 'border-top-color', 'border-right-color',
			'border-bottom-color', 'border-left-color', 'color', 'outline-color'
		]

		# Default values for the background properties
		background_prop_default = {
			'background-image' 			=> 'none',
			'background-size'				=> 'auto',
			'background-repeat' 		=> 'repeat',
			'background-position'		=> '0 0',
			'background-attachment'	=> 'scroll',
			'background-clip'				=> 'border',
			'background-origin'			=> 'padding',
			'background-color'			=> 'transparent',
		}

		# A list of non-W3C color names which get replaced by their hex-codes
		replace_colors = {
			'aliceblue'             => '#F0F8FF',
			'antiquewhite'          => '#FAEBD7',
			'aquamarine'            => '#7FFFD4',
			'azure'                 => '#F0FFFF',
			'beige'                 => '#F5F5DC',
			'bisque'                => '#FFE4C4',
			'blanchedalmond'        => '#FFEBCD',
			'blueviolet'            => '#8A2BE2',
			'brown'                 => '#A52A2A',
			'burlywood'             => '#DEB887',
			'cadetblue'             => '#5F9EA0',
			'chartreuse'            => '#7FFF00',
			'chocolate'             => '#D2691E',
			'coral'                 => '#FF7F50',
			'cornflowerblue'        => '#6495ED',
			'cornsilk'              => '#FFF8DC',
			'crimson'               => '#DC143C',
			'cyan'                  => '#00FFFF',
			'darkblue'              => '#00008B',
			'darkcyan'              => '#008B8B',
			'darkgoldenrod'         => '#B8860B',
			'darkgray'              => '#A9A9A9',
			'darkgreen'             => '#006400',
			'darkkhaki'             => '#BDB76B',
			'darkmagenta'           => '#8B008B',
			'darkolivegreen'        => '#556B2F',
			'darkorange'            => '#FF8C00',
			'darkorchid'            => '#9932CC',
			'darkred'               => '#8B0000',
			'darksalmon'            => '#E9967A',
			'darkseagreen'          => '#8FBC8F',
			'darkslateblue'         => '#483D8B',
			'darkslategray'         => '#2F4F4F',
			'darkturquoise'         => '#00CED1',
			'darkviolet'            => '#9400D3',
			'deeppink'              => '#FF1493',
			'deepskyblue'           => '#00BFFF',
			'dimgray'               => '#696969',
			'dodgerblue'            => '#1E90FF',
			'feldspar'              => '#D19275',
			'firebrick'             => '#B22222',
			'floralwhite'           => '#FFFAF0',
			'forestgreen'           => '#228B22',
			'gainsboro'             => '#DCDCDC',
			'ghostwhite'            => '#F8F8FF',
			'gold'                  => '#FFD700',
			'goldenrod'             => '#DAA520',
			'greenyellow'           => '#ADFF2F',
			'honeydew'              => '#F0FFF0',
			'hotpink'               => '#FF69B4',
			'indianred'             => '#CD5C5C',
			'indigo'                => '#4B0082',
			'ivory'                 => '#FFFFF0',
			'khaki'                 => '#F0E68C',
			'lavender'              => '#E6E6FA',
			'lavenderblush'         => '#FFF0F5',
			'lawngreen'             => '#7CFC00',
			'lemonchiffon'          => '#FFFACD',
			'lightblue'             => '#ADD8E6',
			'lightcoral'            => '#F08080',
			'lightcyan'             => '#E0FFFF',
			'lightgoldenrodyellow'  => '#FAFAD2',
			'lightgrey'             => '#D3D3D3',
			'lightgreen'            => '#90EE90',
			'lightpink'             => '#FFB6C1',
			'lightsalmon'           => '#FFA07A',
			'lightseagreen'         => '#20B2AA',
			'lightskyblue'          => '#87CEFA',
			'lightslateblue'        => '#8470FF',
			'lightslategray'        => '#778899',
			'lightsteelblue'        => '#B0C4DE',
			'lightyellow'           => '#FFFFE0',
			'limegreen'             => '#32CD32',
			'linen'                 => '#FAF0E6',
			'magenta'               => '#FF00FF',
			'mediumaquamarine'      => '#66CDAA',
			'mediumblue'            => '#0000CD',
			'mediumorchid'          => '#BA55D3',
			'mediumpurple'          => '#9370D8',
			'mediumseagreen'        => '#3CB371',
			'mediumslateblue'       => '#7B68EE',
			'mediumspringgreen'     => '#00FA9A',
			'mediumturquoise'       => '#48D1CC',
			'mediumvioletred'       => '#C71585',
			'midnightblue'          => '#191970',
			'mintcream'             => '#F5FFFA',
			'mistyrose'             => '#FFE4E1',
			'moccasin'              => '#FFE4B5',
			'navajowhite'           => '#FFDEAD',
			'oldlace'               => '#FDF5E6',
			'olivedrab'             => '#6B8E23',
			'orangered'             => '#FF4500',
			'orchid'                => '#DA70D6',
			'palegoldenrod'         => '#EEE8AA',
			'palegreen'             => '#98FB98',
			'paleturquoise'         => '#AFEEEE',
			'palevioletred'         => '#D87093',
			'papayawhip'            => '#FFEFD5',
			'peachpuff'             => '#FFDAB9',
			'peru'                  => '#CD853F',
			'pink'                  => '#FFC0CB',
			'plum'                  => '#DDA0DD',
			'powderblue'            => '#B0E0E6',
			'rosybrown'             => '#BC8F8F',
			'royalblue'             => '#4169E1',
			'saddlebrown'           => '#8B4513',
			'salmon'                => '#FA8072',
			'sandybrown'            => '#F4A460',
			'seagreen'              => '#2E8B57',
			'seashell'              => '#FFF5EE',
			'sienna'                => '#A0522D',
			'skyblue'               => '#87CEEB',
			'slateblue'             => '#6A5ACD',
			'slategray'             => '#708090',
			'snow'                  => '#FFFAFA',
			'springgreen'           => '#00FF7F',
			'steelblue'             => '#4682B4',
			'tan'                   => '#D2B48C',
			'thistle'               => '#D8BFD8',
			'tomato'                => '#FF6347',
			'turquoise'             => '#40E0D0',
			'violet'                => '#EE82EE',
			'violetred'             => '#D02090',
			'wheat'                 => '#F5DEB3',
			'whitesmoke'            => '#F5F5F5',
			'yellowgreen'           => '#9ACD32',
		}

		# A list of all shorthand properties that are devided into four properties and/or have four subvalues
		shorthands = {
			'border-color'	=> ['border-top-color','border-right-color','border-bottom-color','border-left-color'],
			'border-style'	=> ['border-top-style','border-right-style','border-bottom-style','border-left-style'],
			'border-width'	=> ['border-top-width','border-right-width','border-bottom-width','border-left-width'],
			'margin'				=> ['margin-top','margin-right','margin-bottom','margin-left'],
			'padding'				=> ['padding-top','padding-right','padding-bottom','padding-left'],
		}

		# All CSS Properties
		PROPERTIES = {
			'background' 						=> '1.0,2.0,2.1',
			'background-color' 			=> '1.0,2.0,2.1',
			'background-image' 			=> '1.0,2.0,2.1',
			'background-repeat' 		=> '1.0,2.0,2.1',
			'background-attachment' => '1.0,2.0,2.1',
			'background-position' 	=> '1.0,2.0,2.1',
			'border' 								=> '1.0,2.0,2.1',
			'border-top' 						=> '1.0,2.0,2.1',
			'border-right' 					=> '1.0,2.0,2.1',
			'border-bottom' 				=> '1.0,2.0,2.1',
			'border-left' 					=> '1.0,2.0,2.1',
			'border-color' 					=> '1.0,2.0,2.1',
			'border-top-color' 			=> '2.0,2.1',
			'border-bottom-color' 	=> '2.0,2.1',
			'border-left-color' 		=> '2.0,2.1',
			'border-right-color'	 	=> '2.0,2.1',
			'border-style' 					=> '1.0,2.0,2.1',
			'border-top-style' 			=> '2.0,2.1',
			'border-right-style' 		=> '2.0,2.1',
			'border-left-style' 		=> '2.0,2.1',
			'border-bottom-style' 	=> '2.0,2.1',
			'border-width' 					=> '1.0,2.0,2.1',
			'border-top-width' 			=> '1.0,2.0,2.1',
			'border-right-width' 		=> '1.0,2.0,2.1',
			'border-left-width' 		=> '1.0,2.0,2.1',
			'border-bottom-width' 	=> '1.0,2.0,2.1',
			'border-collapse' 			=> '2.0,2.1',
			'border-spacing' 				=> '2.0,2.1',
			'bottom' 								=> '2.0,2.1',
			'caption-side' 					=> '2.0,2.1',
			'content' 							=> '2.0,2.1',
			'clear' 								=> '1.0,2.0,2.1',
			'clip' 									=> '1.0,2.0,2.1',
			'color' 								=> '1.0,2.0,2.1',
			'counter-reset' 				=> '2.0,2.1',
			'counter-increment' 		=> '2.0,2.1',
			'cursor'			 					=> '2.0,2.1',
			'empty-cells' 					=> '2.0,2.1',
			'display' 							=> '1.0,2.0,2.1',
			'direction' 						=> '2.0,2.1',
			'float' 								=> '1.0,2.0,2.1',
			'font' 									=> '1.0,2.0,2.1',
			'font-family' 					=> '1.0,2.0,2.1',
			'font-style' 						=> '1.0,2.0,2.1',
			'font-variant' 					=> '1.0,2.0,2.1',
			'font-weight' 					=> '1.0,2.0,2.1',
			'font-stretch' 					=> '2.0',
			'font-size-adjust' 			=> '2.0',
			'font-size' 						=> '1.0,2.0,2.1',
			'height' 								=> '1.0,2.0,2.1',
			'left' 									=> '1.0,2.0,2.1',
			'line-height' 					=> '1.0,2.0,2.1',
			'list-style' 						=> '1.0,2.0,2.1',
			'list-style-type' 			=> '1.0,2.0,2.1',
			'list-style-image' 			=> '1.0,2.0,2.1',
			'list-style-position' 	=> '1.0,2.0,2.1',
			'margin' 								=> '1.0,2.0,2.1',
			'margin-top' 						=> '1.0,2.0,2.1',
			'margin-right' 					=> '1.0,2.0,2.1',
			'margin-bottom' 				=> '1.0,2.0,2.1',
			'margin-left' 					=> '1.0,2.0,2.1',
			'marks' 								=> '1.0,2.0',
			'marker-offset' 				=> '2.0',
			'max-height'			 			=> '2.0,2.1',
			'max-width' 						=> '2.0,2.1',
			'min-height' 						=> '2.0,2.1',
			'min-width' 						=> '2.0,2.1',
			'overflow' 							=> '1.0,2.0,2.1',
			'orphans' 							=> '2.0,2.1',
			'outline' 							=> '2.0,2.1',
			'outline-width' 				=> '2.0,2.1',
			'outline-style' 				=> '2.0,2.1',
			'outline-color' 				=> '2.0,2.1',
			'padding' 							=> '1.0,2.0,2.1',
			'padding-top' 					=> '1.0,2.0,2.1',
			'padding-right' 				=> '1.0,2.0,2.1',
			'padding-bottom' 				=> '1.0,2.0,2.1',
			'padding-left' 					=> '1.0,2.0,2.1',
			'page-break-before' 		=> '1.0,2.0,2.1',
			'page-break-after' 			=> '1.0,2.0,2.1',
			'page-break-inside' 		=> '2.0,2.1',
			'page' 									=> '2.0',
			'position' 							=> '1.0,2.0,2.1',
			'quotes' 								=> '2.0,2.1',
			'right' 								=> '2.0,2.1',
			'size' 									=> '1.0,2.0',
			'speak-header' 					=> '2.0,2.1',
			'table-layout' 					=> '2.0,2.1',
			'top' 									=> '1.0,2.0,2.1',
			'text-indent' 					=> '1.0,2.0,2.1',
			'text-align' 						=> '1.0,2.0,2.1',
			'text-decoration' 			=> '1.0,2.0,2.1',
			'text-shadow' 					=> '2.0',
			'letter-spacing' 				=> '1.0,2.0,2.1',
			'word-spacing' 					=> '1.0,2.0,2.1',
			'text-transform' 				=> '1.0,2.0,2.1',
			'white-space' 					=> '1.0,2.0,2.1',
			'unicode-bidi' 					=> '2.0,2.1',
			'vertical-align' 				=> '1.0,2.0,2.1',
			'visibility' 						=> '1.0,2.0,2.1',
			'width' 								=> '1.0,2.0,2.1',
			'widows' 								=> '2.0,2.1',
			'z-index' 							=> '1.0,2.0,2.1',
			# Speech
			'volume' 								=> '2.0,2.1',
			'speak' 								=> '2.0,2.1',
			'pause' 								=> '2.0,2.1',
			'pause-before' 					=> '2.0,2.1',
			'pause-after'	 					=> '2.0,2.1',
			'cue' 									=> '2.0,2.1',
			'cue-before' 						=> '2.0,2.1',
			'cue-after' 						=> '2.0,2.1',
			'play-during' 					=> '2.0,2.1',
			'azimuth' 							=> '2.0,2.1',
			'elevation' 						=> '2.0,2.1',
			'speech-rate' 					=> '2.0,2.1',
			'voice-family'	 				=> '2.0,2.1',
			'pitch' 								=> '2.0,2.1',
			'pitch-range' 					=> '2.0,2.1',
			'stress' 								=> '2.0,2.1',
			'richness' 							=> '2.0,2.1',
			'speak-punctuation' 		=> '2.0,2.1',
			'speak-numeral' 				=> '2.0,2.1',
		}
	end
end